{% set name = "pytest-black" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d339b004f764d6cd0f06e690f6dd748df3d62e6fe1a692d6a5500ac2c5b75a5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - black >=19.3b0
    - pytest >=3.5.0
    - python >={{ python_min }}
    - toml
test:
  imports:
    - pytest_black
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/shopkeep/pytest-black
  license: MIT
  license_file: LICENSE
  summary: A pytest plugin to enable format checking with black

extra:
  recipe-maintainers:
    - philip-khor
