{% set name = "pytest-black" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c743dfeffe6b2cb25c0ed1a84cc306dff4b504b713b5a6d1bc3824fa73a7d693

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - black >=19.3b0
    - pytest >=3.5.0
    - python >=3.6
    - toml
test:
  imports:
    - pytest_black
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/shopkeep/pytest-black
  license: MIT
  license_file: LICENSE
  summary: A pytest plugin to enable format checking with black

extra:
  recipe-maintainers:
    - philip-khor
