{% set name = "pytest-black" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ecb77455f379805cb4bd8f45a813a3754c3bbee3199adf1b3665c0dfd086b511

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - black >=19.3b0
    - pytest >=3.5.0
    - python >=3.6
    - toml
test:
  imports:
    - pytest_black
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/shopkeep/pytest-black
  license: MIT
  license_file: LICENSE
  summary: A pytest plugin to enable format checking with black

extra:
  recipe-maintainers:
    - philip-khor
